version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/anurag/NewGlobe/NewGlobe/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus configuration file
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Grafana default username
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana default password
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

